spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:teste
    username: admin
    password: 123456
    platform: h2

  jpa:
    hibernate:
      ddl-auto: update

  h2:
  console:
    enabled: true
    path: /h2-console

server:
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /products-api

aws:
  region: us-east-1
  sns:
    topic:
      products:
        events: products-events
  s3:
    bucket:
      invoice-events: invoice-events
  sqs:
    queue:
      products:
        events: products-events
      invoice:
        events: s3-invoice-events

---

spring:
  profiles: prd
  datasource:
    url: jdbc:mariadb://${DB_HOST}/${DB_DATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /products-api

aws:
  region: us-east-1
  sns:
    topic:
      products:
        events: products-events
  s3:
    bucket:
      invoice-events: invoice-events
  sqs:
    queue:
      products:
        events: products-events
      invoice:
        events: s3-invoice-events
